"""initial_schema

Revision ID: 64961c721aad
Revises: 
Create Date: 2026-05-24 14:57:39.448781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64961c721aad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('email', 'form', name='ticketsource', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='ticketstatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='ticketpriority', native_enum=False), nullable=False),
    sa.Column('category', sa.Enum('billing', 'technical', 'general', 'other', name='ticketcategory', native_enum=False), nullable=False),
    sa.Column('escalate', sa.Boolean(), nullable=False),
    sa.Column('ai_draft_reply', sa.Text(), nullable=True),
    sa.Column('agent_reply', sa.Text(), nullable=True),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('triage_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index("idx_agents_email", "agents", ["email"], unique=True)
    op.create_index("idx_magic_tokens_ticket_id", "magic_tokens", ["ticket_id"])
    op.create_index("idx_magic_tokens_token", "magic_tokens", ["token"], unique=True)
    op.create_index("idx_tickets_assigned_agent_id", "tickets", ["assigned_agent_id"])
    op.create_index("idx_tickets_status", "tickets", ["status"])
    op.create_index("idx_tickets_created_at", "tickets", ["created_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magic_tokens')
    op.drop_table('tickets')
    op.drop_table('agents')
    # ### end Alembic commands ###
